name: now_go_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod_annotation: ^2.3.4
  go_router: ^13.2.0
  flutter_screenutil: ^5.9.0
  logger: ^2.0.2+1
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.1
  analyzer: ^6.4.1
  intl: ^0.18.1
  flutter_native_splash: ^2.3.13
  dio: ^5.4.1 # API通信用openapiでも使用
  built_collection: ^5.1.1 # openapiのリストで使用
  openapi: 
    path: lib/openapi/ # openapiのコード生成
  flutter_secure_storage: ^4.2.1
  google_maps_flutter: ^2.2.8
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  permission_handler: ^11.3.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  image_cropper: ^1.5.1
  mime: ^1.0.5
  webview_flutter: ^4.7.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  go_router_builder: ^2.4.1
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#000000"  # スプラッシュスクリーンの背景色を指定します。
  image: assets/images/now_go_logo.png  # スプラッシュスクリーンに使用する画像のパス（プロジェクト内の適切なパスを指定）
  android: true  # Android向けのスプラッシュスクリーンを有効にするかどうか
  ios: true  # iOS向けのスプラッシュスクリーンを有効にするかどうか
  fullscreen: true #スプラッシュスクリーンを画面全体にしたい時はtrueを指定します。