name: spot_gab_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  go_router: ^13.2.0
  flutter_screenutil: ^5.9.0
  logger: ^2.0.2+1
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.1
  analyzer: ^6.4.1
  intl: ^0.18.1
  flutter_native_splash: ^2.3.13
  dio: ^5.4.1 # API通信用openapiでも使用
  built_collection: ^5.1.1 # openapiのリストで使用
  openapi: 
    path: lib/gen/openapi # openapiのコード生成
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"  # スプラッシュスクリーンの背景色を指定します。
  image: assets/images/spot_gab_splash_icon.png  # スプラッシュスクリーンに使用する画像のパス（プロジェクト内の適切なパスを指定）
  android: true  # Android向けのスプラッシュスクリーンを有効にするかどうか
  ios: true  # iOS向けのスプラッシュスクリーンを有効にするかどうか
  fullscreen: true #スプラッシュスクリーンを画面全体にしたい時はtrueを指定します。